services:
  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: builder
    command: npm run start:dev product
    env_file:
      - ./apps/product/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: builder
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
